export default {
  type: 'FeatureCollection',
  name: 'week_6',
  crs: { type: 'name', properties: { name: 'urn:ogc:def:crs:OGC:1.3:CRS84' } },
  features: [
    {
      type: 'Feature',
      properties: {
        field_1: 0,
        trek: 1,
        wachtsman: null,
        tijd: '07:55',
        datum: '4-2-2018',
        lat: "51°20'",
        long: "02°54'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 3,
        'tijd halen': '09:20',
        schatting: null,
        totaal_kg: 45,
        tong: 25,
        schol: 15.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.2,
        new_long: 2.54
      },
      geometry: { type: 'Point', coordinates: [2.54, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 1,
        trek: 2,
        wachtsman: null,
        tijd: '09:30',
        datum: '4-2-2018',
        lat: "51°20'",
        long: "02°54'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 4,
        'tijd halen': '11:10',
        schatting: null,
        totaal_kg: 45,
        tong: 25,
        schol: 15.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.2,
        new_long: 2.54
      },
      geometry: { type: 'Point', coordinates: [2.54, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 2,
        trek: 3,
        wachtsman: null,
        tijd: '11:20',
        datum: '4-2-2018',
        lat: "51°16'",
        long: "02°54'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 4,
        'tijd halen': '12:40',
        schatting: null,
        totaal_kg: 45,
        tong: 25,
        schol: 15.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.16,
        new_long: 2.54
      },
      geometry: { type: 'Point', coordinates: [2.54, 51.16] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 3,
        trek: 4,
        wachtsman: null,
        tijd: '12:50',
        datum: '4-2-2018',
        lat: "51°20'",
        long: "02°45'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 4,
        'tijd halen': '14:20',
        schatting: null,
        totaal_kg: 30,
        tong: 20,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.2,
        new_long: 2.45
      },
      geometry: { type: 'Point', coordinates: [2.45, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 4,
        trek: 5,
        wachtsman: null,
        tijd: '14:30',
        datum: '4-2-2018',
        lat: "51°14'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '16:00',
        schatting: null,
        totaal_kg: 35,
        tong: 20,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.14,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.14] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 5,
        trek: 6,
        wachtsman: null,
        tijd: '16:10',
        datum: '4-2-2018',
        lat: "51°15'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '17:40',
        schatting: null,
        totaal_kg: 30,
        tong: 20,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.15,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.15] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 6,
        trek: 7,
        wachtsman: null,
        tijd: '17:45',
        datum: '4-2-2018',
        lat: "51°16'",
        long: "02°55'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '19:15',
        schatting: null,
        totaal_kg: 40,
        tong: 25,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.16,
        new_long: 2.55
      },
      geometry: { type: 'Point', coordinates: [2.55, 51.16] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 7,
        trek: 8,
        wachtsman: null,
        tijd: '19:25',
        datum: '4-2-2018',
        lat: "51°21'",
        long: "02°54'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '20:55',
        schatting: null,
        totaal_kg: 35,
        tong: 20,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.21,
        new_long: 2.54
      },
      geometry: { type: 'Point', coordinates: [2.54, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 8,
        trek: 9,
        wachtsman: null,
        tijd: '21:05',
        datum: '4-2-2018',
        lat: "51°23'",
        long: "02°58'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '22:35',
        schatting: null,
        totaal_kg: 30,
        tong: 20,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.23,
        new_long: 2.58
      },
      geometry: { type: 'Point', coordinates: [2.58, 51.23] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 9,
        trek: 10,
        wachtsman: null,
        tijd: '22:45',
        datum: '4-2-2018',
        lat: "51°19'",
        long: "02°53'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '00:15',
        schatting: null,
        totaal_kg: 25,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.19,
        new_long: 2.53
      },
      geometry: { type: 'Point', coordinates: [2.53, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 10,
        trek: 11,
        wachtsman: null,
        tijd: '00:25',
        datum: '5-2-2018',
        lat: "51°21'",
        long: "02°54'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '01:55',
        schatting: null,
        totaal_kg: 30,
        tong: 20,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.21,
        new_long: 2.54
      },
      geometry: { type: 'Point', coordinates: [2.54, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 11,
        trek: 12,
        wachtsman: null,
        tijd: '02:10',
        datum: '5-2-2018',
        lat: "51°20'",
        long: "02°54'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 7,
        'tijd halen': '03:40',
        schatting: null,
        totaal_kg: 20,
        tong: 5,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.2,
        new_long: 2.54
      },
      geometry: { type: 'Point', coordinates: [2.54, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 12,
        trek: 13,
        wachtsman: null,
        tijd: '03:50',
        datum: '5-2-2018',
        lat: "51°25'",
        long: "02°58'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 7,
        'tijd halen': '04:10',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.25,
        new_long: 2.58
      },
      geometry: { type: 'Point', coordinates: [2.58, 51.25] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 13,
        trek: 14,
        wachtsman: null,
        tijd: '04:50',
        datum: '5-2-2018',
        lat: "51°27'",
        long: "03°01'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 7,
        'tijd halen': '06:10',
        schatting: null,
        totaal_kg: 20,
        tong: 10,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.27,
        new_long: 3.01
      },
      geometry: { type: 'Point', coordinates: [3.01, 51.27] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 14,
        trek: 15,
        wachtsman: null,
        tijd: '06:20',
        datum: '5-2-2018',
        lat: "51°30'",
        long: "03°09'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '07:00',
        schatting: null,
        totaal_kg: 25,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.3,
        new_long: 3.09
      },
      geometry: { type: 'Point', coordinates: [3.09, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 15,
        trek: 16,
        wachtsman: null,
        tijd: '07:10',
        datum: '5-2-2018',
        lat: "51°32'",
        long: "03°13'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '08:30',
        schatting: null,
        totaal_kg: 35,
        tong: 25,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.32,
        new_long: 3.13
      },
      geometry: { type: 'Point', coordinates: [3.13, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 16,
        trek: 17,
        wachtsman: null,
        tijd: '09:20',
        datum: '5-2-2018',
        lat: "51°35'",
        long: "03°17'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '10:50',
        schatting: null,
        totaal_kg: 40,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.35,
        new_long: 3.17
      },
      geometry: { type: 'Point', coordinates: [3.17, 51.35] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 17,
        trek: 18,
        wachtsman: null,
        tijd: '11:00',
        datum: '5-2-2018',
        lat: "51°30'",
        long: "03°08'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '12:30',
        schatting: null,
        totaal_kg: 30,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.3,
        new_long: 3.08
      },
      geometry: { type: 'Point', coordinates: [3.08, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 18,
        trek: 19,
        wachtsman: null,
        tijd: '13:00',
        datum: '5-2-2018',
        lat: "51°25'",
        long: "02°58'",
        snelheid: 4.5,
        richting: 'o',
        'kracht (Bft)': 5,
        'tijd halen': '14:30',
        schatting: null,
        totaal_kg: 40,
        tong: 25,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.25,
        new_long: 2.58
      },
      geometry: { type: 'Point', coordinates: [2.58, 51.25] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 19,
        trek: 20,
        wachtsman: null,
        tijd: '14:35',
        datum: '5-2-2018',
        lat: "51°19'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'o',
        'kracht (Bft)': 5,
        'tijd halen': '16:05',
        schatting: null,
        totaal_kg: 25,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.19,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 20,
        trek: 21,
        wachtsman: null,
        tijd: '16:15',
        datum: '5-2-2018',
        lat: "51°18'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'o',
        'kracht (Bft)': 5,
        'tijd halen': '17:45',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.18,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 21,
        trek: 22,
        wachtsman: null,
        tijd: '18:00',
        datum: '5-2-2018',
        lat: "51°19'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'o',
        'kracht (Bft)': 6,
        'tijd halen': '19:30',
        schatting: null,
        totaal_kg: 40,
        tong: 25,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.19,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 22,
        trek: 23,
        wachtsman: null,
        tijd: '19:40',
        datum: '5-2-2018',
        lat: "51°19'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'o',
        'kracht (Bft)': 6,
        'tijd halen': '21:00',
        schatting: null,
        totaal_kg: 40,
        tong: 25,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.19,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 23,
        trek: 24,
        wachtsman: null,
        tijd: '21:10',
        datum: '5-2-2018',
        lat: "51°21'",
        long: "02°55'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 7,
        'tijd halen': '22:35',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.21,
        new_long: 2.55
      },
      geometry: { type: 'Point', coordinates: [2.55, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 24,
        trek: 25,
        wachtsman: null,
        tijd: '22:45',
        datum: '5-2-2018',
        lat: "51°21'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 7,
        'tijd halen': '00:15',
        schatting: null,
        totaal_kg: 25,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.21,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 25,
        trek: 26,
        wachtsman: null,
        tijd: '00:25',
        datum: '6-2-2018',
        lat: "51°19'",
        long: "02°50'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 7,
        'tijd halen': '02:00',
        schatting: null,
        totaal_kg: 30,
        tong: 20,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.19,
        new_long: 2.5
      },
      geometry: { type: 'Point', coordinates: [2.5, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 26,
        trek: 27,
        wachtsman: null,
        tijd: '02:05',
        datum: '6-2-2018',
        lat: "51°20'",
        long: "02°52'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '03:30',
        schatting: null,
        totaal_kg: 40,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.2,
        new_long: 2.52
      },
      geometry: { type: 'Point', coordinates: [2.52, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 27,
        trek: 28,
        wachtsman: null,
        tijd: '03:35',
        datum: '6-2-2018',
        lat: "51°16'",
        long: "02°43'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '05:05',
        schatting: null,
        totaal_kg: 25,
        tong: 10,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.16,
        new_long: 2.43
      },
      geometry: { type: 'Point', coordinates: [2.43, 51.16] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 28,
        trek: 29,
        wachtsman: null,
        tijd: '05:15',
        datum: '6-2-2018',
        lat: "51°19'",
        long: "02°50'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '06:40',
        schatting: null,
        totaal_kg: 35,
        tong: 20,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 60.0,
        schar: 60.0,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.19,
        new_long: 2.5
      },
      geometry: { type: 'Point', coordinates: [2.5, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 29,
        trek: 30,
        wachtsman: null,
        tijd: '06:50',
        datum: '6-2-2018',
        lat: "51°15'",
        long: "02°43'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '08:10',
        schatting: null,
        totaal_kg: 35,
        tong: 30,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.15,
        new_long: 2.43
      },
      geometry: { type: 'Point', coordinates: [2.43, 51.15] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 30,
        trek: 31,
        wachtsman: null,
        tijd: '08:20',
        datum: '6-2-2018',
        lat: "51°19'",
        long: "02°50'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 5,
        'tijd halen': '09:50',
        schatting: null,
        totaal_kg: 40,
        tong: 25,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.19,
        new_long: 2.5
      },
      geometry: { type: 'Point', coordinates: [2.5, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 31,
        trek: 32,
        wachtsman: null,
        tijd: '10:00',
        datum: '6-2-2018',
        lat: "51°17'",
        long: "02°44'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '11:35',
        schatting: null,
        totaal_kg: 35,
        tong: 20,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.17,
        new_long: 2.44
      },
      geometry: { type: 'Point', coordinates: [2.44, 51.17] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 32,
        trek: 33,
        wachtsman: null,
        tijd: '11:45',
        datum: '6-2-2018',
        lat: "51°18'",
        long: "02°43'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '13:15',
        schatting: null,
        totaal_kg: 35,
        tong: 20,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.18,
        new_long: 2.43
      },
      geometry: { type: 'Point', coordinates: [2.43, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 33,
        trek: 34,
        wachtsman: null,
        tijd: '13:30',
        datum: '6-2-2018',
        lat: "51°19'",
        long: "02°50'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '14:35',
        schatting: null,
        totaal_kg: 25,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.19,
        new_long: 2.5
      },
      geometry: { type: 'Point', coordinates: [2.5, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 34,
        trek: 35,
        wachtsman: null,
        tijd: '14:45',
        datum: '6-2-2018',
        lat: "51°16'",
        long: "02°44'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '16:30',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.16,
        new_long: 2.44
      },
      geometry: { type: 'Point', coordinates: [2.44, 51.16] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 35,
        trek: 36,
        wachtsman: null,
        tijd: '16:40',
        datum: '6-2-2018',
        lat: "51°18'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '17:40',
        schatting: null,
        totaal_kg: 35,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.18,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 36,
        trek: 37,
        wachtsman: null,
        tijd: '17:50',
        datum: '6-2-2018',
        lat: "51°18'",
        long: "02°45'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '19:20',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.18,
        new_long: 2.45
      },
      geometry: { type: 'Point', coordinates: [2.45, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 37,
        trek: 38,
        wachtsman: null,
        tijd: '19:30',
        datum: '6-2-2018',
        lat: "51°23'",
        long: "02°54'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '20:45',
        schatting: null,
        totaal_kg: 30,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.23,
        new_long: 2.54
      },
      geometry: { type: 'Point', coordinates: [2.54, 51.23] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 38,
        trek: 39,
        wachtsman: null,
        tijd: '20:55',
        datum: '6-2-2018',
        lat: "51°27'",
        long: "03°01'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '22:15',
        schatting: null,
        totaal_kg: 35,
        tong: 20,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.27,
        new_long: 3.01
      },
      geometry: { type: 'Point', coordinates: [3.01, 51.27] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 39,
        trek: 40,
        wachtsman: null,
        tijd: '22:25',
        datum: '6-2-2018',
        lat: "51°28'",
        long: "03°00'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '00:05',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.28,
        new_long: 3.0
      },
      geometry: { type: 'Point', coordinates: [3.0, 51.28] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 40,
        trek: 41,
        wachtsman: null,
        tijd: '00:10',
        datum: '7-2-2018',
        lat: "51°23'",
        long: "03°00'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '01:40',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.23,
        new_long: 3.0
      },
      geometry: { type: 'Point', coordinates: [3.0, 51.23] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 41,
        trek: 42,
        wachtsman: null,
        tijd: '01:50',
        datum: '7-2-2018',
        lat: "51°20'",
        long: "02°50'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '03:20',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.2,
        new_long: 2.5
      },
      geometry: { type: 'Point', coordinates: [2.5, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 42,
        trek: 43,
        wachtsman: null,
        tijd: '03:30',
        datum: '7-2-2018',
        lat: "51°18'",
        long: "02°45'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '04:55',
        schatting: null,
        totaal_kg: 35,
        tong: 15,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.18,
        new_long: 2.45
      },
      geometry: { type: 'Point', coordinates: [2.45, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 43,
        trek: 44,
        wachtsman: null,
        tijd: '05:05',
        datum: '7-2-2018',
        lat: "51°20'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '06:15',
        schatting: null,
        totaal_kg: 35,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: 20.0,
        griet: null,
        rog: 20.0,
        opmerkingen: null,
        bot: 60.0,
        schar: 60.0,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.2,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 44,
        trek: 45,
        wachtsman: null,
        tijd: '06:25',
        datum: '7-2-2018',
        lat: "51°20'",
        long: "02°48'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '07:30',
        schatting: null,
        totaal_kg: 35,
        tong: 20,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.2,
        new_long: 2.48
      },
      geometry: { type: 'Point', coordinates: [2.48, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 45,
        trek: 46,
        wachtsman: null,
        tijd: '07:45',
        datum: '7-2-2018',
        lat: "51°21'",
        long: "02°49'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '08:45',
        schatting: null,
        totaal_kg: 35,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.21,
        new_long: 2.49
      },
      geometry: { type: 'Point', coordinates: [2.49, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 46,
        trek: 47,
        wachtsman: null,
        tijd: '08:55',
        datum: '7-2-2018',
        lat: "51°21'",
        long: "02°51'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '10:05',
        schatting: null,
        totaal_kg: 35,
        tong: 20,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.21,
        new_long: 2.51
      },
      geometry: { type: 'Point', coordinates: [2.51, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 47,
        trek: 48,
        wachtsman: null,
        tijd: '10:15',
        datum: '7-2-2018',
        lat: "51°21'",
        long: "02°51'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '11:30',
        schatting: null,
        totaal_kg: 35,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.21,
        new_long: 2.51
      },
      geometry: { type: 'Point', coordinates: [2.51, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 48,
        trek: 49,
        wachtsman: null,
        tijd: '11:45',
        datum: '7-2-2018',
        lat: "51°21'",
        long: "02°51'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '12:45',
        schatting: null,
        totaal_kg: 40,
        tong: 20,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.21,
        new_long: 2.51
      },
      geometry: { type: 'Point', coordinates: [2.51, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 49,
        trek: 50,
        wachtsman: null,
        tijd: '14:50',
        datum: '7-2-2018',
        lat: "51°22'",
        long: "02°51'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '16:15',
        schatting: null,
        totaal_kg: 25,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.22,
        new_long: 2.51
      },
      geometry: { type: 'Point', coordinates: [2.51, 51.22] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 50,
        trek: 51,
        wachtsman: null,
        tijd: '16:25',
        datum: '7-2-2018',
        lat: "51°21'",
        long: "02°50'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '18:00',
        schatting: null,
        totaal_kg: 15,
        tong: 2,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.21,
        new_long: 2.5
      },
      geometry: { type: 'Point', coordinates: [2.5, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 51,
        trek: 52,
        wachtsman: null,
        tijd: '19:30',
        datum: '7-2-2018',
        lat: "51°22'",
        long: "02°50'",
        snelheid: 4.5,
        richting: 'ono',
        'kracht (Bft)': 4,
        'tijd halen': '20:35',
        schatting: null,
        totaal_kg: 30,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.22,
        new_long: 2.5
      },
      geometry: { type: 'Point', coordinates: [2.5, 51.22] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 52,
        trek: 53,
        wachtsman: null,
        tijd: '20:45',
        datum: '7-2-2018',
        lat: "51°22'",
        long: "02°50'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 4,
        'tijd halen': '22:00',
        schatting: null,
        totaal_kg: 55,
        tong: 20,
        schol: 30.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.22,
        new_long: 2.5
      },
      geometry: { type: 'Point', coordinates: [2.5, 51.22] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 53,
        trek: 54,
        wachtsman: null,
        tijd: '22:10',
        datum: '7-2-2018',
        lat: "51°22'",
        long: "02°50'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 4,
        'tijd halen': '23:10',
        schatting: null,
        totaal_kg: 20,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.22,
        new_long: 2.5
      },
      geometry: { type: 'Point', coordinates: [2.5, 51.22] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 54,
        trek: 55,
        wachtsman: null,
        tijd: '23:20',
        datum: '7-2-2018',
        lat: "51°22'",
        long: "02°53'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '00:30',
        schatting: null,
        totaal_kg: 40,
        tong: 10,
        schol: 20.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.22,
        new_long: 2.53
      },
      geometry: { type: 'Point', coordinates: [2.53, 51.22] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 55,
        trek: 56,
        wachtsman: null,
        tijd: '00:35',
        datum: '8-2-2018',
        lat: "51°18'",
        long: "02°51'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '02:05',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.18,
        new_long: 2.51
      },
      geometry: { type: 'Point', coordinates: [2.51, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 56,
        trek: 57,
        wachtsman: null,
        tijd: '02:15',
        datum: '8-2-2018',
        lat: "51°19'",
        long: "02°46'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '02:30',
        schatting: null,
        totaal_kg: 25,
        tong: 10,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.19,
        new_long: 2.46
      },
      geometry: { type: 'Point', coordinates: [2.46, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 57,
        trek: 58,
        wachtsman: null,
        tijd: '04:00',
        datum: '8-2-2018',
        lat: "51°20'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '05:15',
        schatting: null,
        totaal_kg: 15,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.2,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 58,
        trek: 59,
        wachtsman: null,
        tijd: '05:20',
        datum: '8-2-2018',
        lat: "51°20'",
        long: "02°48'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '06:35',
        schatting: null,
        totaal_kg: 15,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.2,
        new_long: 2.48
      },
      geometry: { type: 'Point', coordinates: [2.48, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 59,
        trek: 60,
        wachtsman: null,
        tijd: '06:45',
        datum: '8-2-2018',
        lat: "51°22'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '08:00',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.22,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.22] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 60,
        trek: 61,
        wachtsman: null,
        tijd: '08:10',
        datum: '8-2-2018',
        lat: "51°27'",
        long: "02°54'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '09:00',
        schatting: null,
        totaal_kg: 15,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.27,
        new_long: 2.54
      },
      geometry: { type: 'Point', coordinates: [2.54, 51.27] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 61,
        trek: 62,
        wachtsman: null,
        tijd: '09:15',
        datum: '8-2-2018',
        lat: "51°29'",
        long: "02°59'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '10:25',
        schatting: null,
        totaal_kg: 20,
        tong: 10,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.29,
        new_long: 2.59
      },
      geometry: { type: 'Point', coordinates: [2.59, 51.29] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 62,
        trek: 63,
        wachtsman: null,
        tijd: '10:30',
        datum: '8-2-2018',
        lat: "51°28'",
        long: "03°08'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '11:45',
        schatting: null,
        totaal_kg: 35,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: 20.0,
        rog: null,
        opmerkingen: null,
        bot: 50.0,
        schar: 80.0,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.28,
        new_long: 3.08
      },
      geometry: { type: 'Point', coordinates: [3.08, 51.28] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 63,
        trek: 64,
        wachtsman: null,
        tijd: '11:55',
        datum: '8-2-2018',
        lat: "51°33'",
        long: "03°05'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '13:10',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.33,
        new_long: 3.05
      },
      geometry: { type: 'Point', coordinates: [3.05, 51.33] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 64,
        trek: 65,
        wachtsman: null,
        tijd: '13:20',
        datum: '8-2-2018',
        lat: "51°34'",
        long: "03°15'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '14:40',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.34,
        new_long: 3.15
      },
      geometry: { type: 'Point', coordinates: [3.15, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 65,
        trek: 66,
        wachtsman: null,
        tijd: '14:50',
        datum: '8-2-2018',
        lat: "51°35'",
        long: "03°17'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '16:05',
        schatting: null,
        totaal_kg: 30,
        tong: 20,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.35,
        new_long: 3.17
      },
      geometry: { type: 'Point', coordinates: [3.17, 51.35] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 66,
        trek: 67,
        wachtsman: null,
        tijd: '16:15',
        datum: '8-2-2018',
        lat: "51°34'",
        long: "03°18'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '17:00',
        schatting: null,
        totaal_kg: 30,
        tong: 20,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        'Unnamed: 21': null,
        'Unnamed: 22': null,
        'Unnamed: 23': null,
        'Unnamed: 24': null,
        'Unnamed: 25': null,
        'Unnamed: 26': null,
        'Unnamed: 27': null,
        'Unnamed: 28': null,
        'Unnamed: 29': null,
        'Unnamed: 30': null,
        'Unnamed: 31': null,
        'Unnamed: 32': null,
        'Unnamed: 33': null,
        'Unnamed: 34': null,
        'Unnamed: 35': null,
        'Unnamed: 36': null,
        'Unnamed: 37': null,
        'Unnamed: 38': null,
        new_lat: 51.34,
        new_long: 3.18
      },
      geometry: { type: 'Point', coordinates: [3.18, 51.34] }
    }
  ]
}
