export default {
  type: 'FeatureCollection',
  name: 'week_4',
  crs: { type: 'name', properties: { name: 'urn:ogc:def:crs:OGC:1.3:CRS84' } },
  features: [
    {
      type: 'Feature',
      properties: {
        field_1: 0,
        trek: 1,
        wachtsman: null,
        tijd: '21:00',
        datum: '23-1-2018',
        lat: "51°34'",
        long: "03°14'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 5,
        'tijd halen': '22:30',
        schatting: null,
        totaal_kg: 30,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: 5.0,
        new_lat: 51.34,
        new_long: 3.14
      },
      geometry: { type: 'Point', coordinates: [3.14, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 1,
        trek: 2,
        wachtsman: null,
        tijd: '22:40',
        datum: '23-1-2018',
        lat: "51°36'",
        long: "03°18'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 5,
        'tijd halen': '00:10',
        schatting: null,
        totaal_kg: 30,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.36,
        new_long: 3.18
      },
      geometry: { type: 'Point', coordinates: [3.18, 51.36] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 2,
        trek: 3,
        wachtsman: null,
        tijd: '00:20',
        datum: '24-1-2018',
        lat: "51°34'",
        long: "03°14'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 6,
        'tijd halen': '01:45',
        schatting: null,
        totaal_kg: 25,
        tong: 24,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.14
      },
      geometry: { type: 'Point', coordinates: [3.14, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 3,
        trek: 4,
        wachtsman: null,
        tijd: '01:55',
        datum: '24-1-2018',
        lat: "51°36'",
        long: "03°18'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 5,
        'tijd halen': '03:25',
        schatting: null,
        totaal_kg: 27,
        tong: 22,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: null,
        new_lat: 51.36,
        new_long: 3.18
      },
      geometry: { type: 'Point', coordinates: [3.18, 51.36] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 4,
        trek: 5,
        wachtsman: null,
        tijd: '03:35',
        datum: '24-1-2018',
        lat: "51°34'",
        long: "03°13'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 5,
        'tijd halen': '05:05',
        schatting: null,
        totaal_kg: 30,
        tong: 28,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: 1.0,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.13
      },
      geometry: { type: 'Point', coordinates: [3.13, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 5,
        trek: 6,
        wachtsman: null,
        tijd: '05:15',
        datum: '24-1-2018',
        lat: "51°37'",
        long: "03°20'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 5,
        'tijd halen': '06:45',
        schatting: null,
        totaal_kg: 30,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: 2.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.37,
        new_long: 3.2
      },
      geometry: { type: 'Point', coordinates: [3.2, 51.37] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 6,
        trek: 7,
        wachtsman: null,
        tijd: '06:55',
        datum: '24-1-2018',
        lat: "51°34'",
        long: "03°14'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 4,
        'tijd halen': '07:50',
        schatting: null,
        totaal_kg: 15,
        tong: 12,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: 2.0,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.14
      },
      geometry: { type: 'Point', coordinates: [3.14, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 7,
        trek: 8,
        wachtsman: null,
        tijd: '08:05',
        datum: '24-1-2018',
        lat: "51°37'",
        long: "03°20'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 5,
        'tijd halen': '09:35',
        schatting: null,
        totaal_kg: 20,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.37,
        new_long: 3.2
      },
      geometry: { type: 'Point', coordinates: [3.2, 51.37] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 8,
        trek: 9,
        wachtsman: null,
        tijd: '09:45',
        datum: '24-1-2018',
        lat: "51°34'",
        long: "03°14'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 5,
        'tijd halen': '11:10',
        schatting: null,
        totaal_kg: 40,
        tong: 30,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: 5.0,
        new_lat: 51.34,
        new_long: 3.14
      },
      geometry: { type: 'Point', coordinates: [3.14, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 9,
        trek: 10,
        wachtsman: null,
        tijd: '11:20',
        datum: '24-1-2018',
        lat: "51°35'",
        long: "03°17'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 7,
        'tijd halen': '12:45',
        schatting: null,
        totaal_kg: 30,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.35,
        new_long: 3.17
      },
      geometry: { type: 'Point', coordinates: [3.17, 51.35] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 10,
        trek: 11,
        wachtsman: null,
        tijd: '12:55',
        datum: '24-1-2018',
        lat: "51°35'",
        long: "03°17'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 7,
        'tijd halen': '14:25',
        schatting: null,
        totaal_kg: 30,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.35,
        new_long: 3.17
      },
      geometry: { type: 'Point', coordinates: [3.17, 51.35] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 11,
        trek: 12,
        wachtsman: null,
        tijd: '14:35',
        datum: '24-1-2018',
        lat: "51°35'",
        long: "03°15'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 6,
        'tijd halen': '16:00',
        schatting: null,
        totaal_kg: 35,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: null,
        new_lat: 51.35,
        new_long: 3.15
      },
      geometry: { type: 'Point', coordinates: [3.15, 51.35] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 12,
        trek: 13,
        wachtsman: null,
        tijd: '16:10',
        datum: '24-1-2018',
        lat: "51°35'",
        long: "03°16'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 6,
        'tijd halen': '17:25',
        schatting: null,
        totaal_kg: 15,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.35,
        new_long: 3.16
      },
      geometry: { type: 'Point', coordinates: [3.16, 51.35] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 13,
        trek: 14,
        wachtsman: null,
        tijd: '17:35',
        datum: '24-1-2018',
        lat: "51°33'",
        long: "03°10'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 6,
        'tijd halen': '18:30',
        schatting: null,
        totaal_kg: 5,
        tong: 4,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.33,
        new_long: 3.1
      },
      geometry: { type: 'Point', coordinates: [3.1, 51.33] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 14,
        trek: 15,
        wachtsman: null,
        tijd: '18:40',
        datum: '24-1-2018',
        lat: "51°34'",
        long: "03°12'",
        snelheid: 4.5,
        richting: 'w',
        'kracht (Bft)': 4,
        'tijd halen': '20:05',
        schatting: null,
        totaal_kg: 35,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: null,
        new_lat: 51.34,
        new_long: 3.12
      },
      geometry: { type: 'Point', coordinates: [3.12, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 15,
        trek: 16,
        wachtsman: null,
        tijd: '02:15',
        datum: '25-1-2018',
        lat: "51°36'",
        long: "03°19'",
        snelheid: 4.5,
        richting: 'w',
        'kracht (Bft)': 4,
        'tijd halen': '21:25',
        schatting: null,
        totaal_kg: 5,
        tong: 5,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.36,
        new_long: 3.19
      },
      geometry: { type: 'Point', coordinates: [3.19, 51.36] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 16,
        trek: 17,
        wachtsman: null,
        tijd: '21:35',
        datum: '25-1-2018',
        lat: "51°35'",
        long: "03°17'",
        snelheid: 4.5,
        richting: 'w',
        'kracht (Bft)': 4,
        'tijd halen': '22:30',
        schatting: null,
        totaal_kg: 30,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.35,
        new_long: 3.17
      },
      geometry: { type: 'Point', coordinates: [3.17, 51.35] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 17,
        trek: 18,
        wachtsman: null,
        tijd: '22:40',
        datum: '25-1-2018',
        lat: "51°34'",
        long: "03°15'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 4,
        'tijd halen': '23:35',
        schatting: null,
        totaal_kg: 15,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.15
      },
      geometry: { type: 'Point', coordinates: [3.15, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 18,
        trek: 19,
        wachtsman: null,
        tijd: '23:45',
        datum: '25-1-2018',
        lat: "51°33'",
        long: "03°14'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 4,
        'tijd halen': '00:45',
        schatting: null,
        totaal_kg: 20,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.33,
        new_long: 3.14
      },
      geometry: { type: 'Point', coordinates: [3.14, 51.33] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 19,
        trek: 20,
        wachtsman: null,
        tijd: '00:55',
        datum: '26-1-2018',
        lat: "51°34'",
        long: "03°15'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 4,
        'tijd halen': '01:55',
        schatting: null,
        totaal_kg: 15,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.15
      },
      geometry: { type: 'Point', coordinates: [3.15, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 20,
        trek: 21,
        wachtsman: null,
        tijd: '02:05',
        datum: '26-1-2018',
        lat: "51°32'",
        long: "03°07'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 4,
        'tijd halen': '03:05',
        schatting: null,
        totaal_kg: 15,
        tong: 13,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.32,
        new_long: 3.07
      },
      geometry: { type: 'Point', coordinates: [3.07, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 21,
        trek: 22,
        wachtsman: null,
        tijd: '03:15',
        datum: '26-1-2018',
        lat: "51°29'",
        long: "03°00'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 4,
        'tijd halen': '04:35',
        schatting: null,
        totaal_kg: 10,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.29,
        new_long: 3.0
      },
      geometry: { type: 'Point', coordinates: [3.0, 51.29] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 22,
        trek: 23,
        wachtsman: null,
        tijd: '04:45',
        datum: '26-1-2018',
        lat: "51°29'",
        long: "02°59'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 4,
        'tijd halen': '06:05',
        schatting: null,
        totaal_kg: 12,
        tong: 12,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.29,
        new_long: 2.59
      },
      geometry: { type: 'Point', coordinates: [2.59, 51.29] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 23,
        trek: 24,
        wachtsman: null,
        tijd: '06:15',
        datum: '26-1-2018',
        lat: "51°30'",
        long: "02°52'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 4,
        'tijd halen': '07:30',
        schatting: null,
        totaal_kg: 20,
        tong: 13,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.3,
        new_long: 2.52
      },
      geometry: { type: 'Point', coordinates: [2.52, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 24,
        trek: 25,
        wachtsman: null,
        tijd: '07:40',
        datum: '26-1-2018',
        lat: "51°32'",
        long: "02°46'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 4,
        'tijd halen': '09:00',
        schatting: null,
        totaal_kg: 10,
        tong: 5,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.32,
        new_long: 2.46
      },
      geometry: { type: 'Point', coordinates: [2.46, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 25,
        trek: 26,
        wachtsman: null,
        tijd: '09:10',
        datum: '26-1-2018',
        lat: "51°30'",
        long: "02°41'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 4,
        'tijd halen': '10:25',
        schatting: null,
        totaal_kg: 20,
        tong: 15,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.3,
        new_long: 2.41
      },
      geometry: { type: 'Point', coordinates: [2.41, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 26,
        trek: 27,
        wachtsman: null,
        tijd: '10:35',
        datum: '26-1-2018',
        lat: "51°25'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 4,
        'tijd halen': '12:10',
        schatting: null,
        totaal_kg: 40,
        tong: 20,
        schol: 10.0,
        kabeljauw: 5.0,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.25,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.25] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 27,
        trek: 28,
        wachtsman: null,
        tijd: '12:20',
        datum: '26-1-2018',
        lat: "51°21'",
        long: "02°40'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 4,
        'tijd halen': '13:40',
        schatting: null,
        totaal_kg: 65,
        tong: 20,
        schol: 40.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.21,
        new_long: 2.4
      },
      geometry: { type: 'Point', coordinates: [2.4, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 28,
        trek: 29,
        wachtsman: null,
        tijd: '13:50',
        datum: '26-1-2018',
        lat: "51°15'",
        long: "02°35'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 4,
        'tijd halen': '15:15',
        schatting: null,
        totaal_kg: 15,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.15,
        new_long: 2.35
      },
      geometry: { type: 'Point', coordinates: [2.35, 51.15] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 29,
        trek: 30,
        wachtsman: null,
        tijd: '15:25',
        datum: '26-1-2018',
        lat: "51°15'",
        long: "02°35'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 4,
        'tijd halen': '16:45',
        schatting: null,
        totaal_kg: 10,
        tong: 5,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.15,
        new_long: 2.35
      },
      geometry: { type: 'Point', coordinates: [2.35, 51.15] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 30,
        trek: 31,
        wachtsman: null,
        tijd: '16:55',
        datum: '26-1-2018',
        lat: "51°18'",
        long: "02°37'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '18:20',
        schatting: null,
        totaal_kg: 55,
        tong: 15,
        schol: 35.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.18,
        new_long: 2.37
      },
      geometry: { type: 'Point', coordinates: [2.37, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 31,
        trek: 32,
        wachtsman: null,
        tijd: '18:30',
        datum: '26-1-2018',
        lat: "51°19'",
        long: "02°38'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '19:50',
        schatting: null,
        totaal_kg: 55,
        tong: 20,
        schol: 25.0,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.19,
        new_long: 2.38
      },
      geometry: { type: 'Point', coordinates: [2.38, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 32,
        trek: 33,
        wachtsman: null,
        tijd: '20:00',
        datum: '26-1-2018',
        lat: "51°19'",
        long: "02°40'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '21:25',
        schatting: null,
        totaal_kg: 55,
        tong: 20,
        schol: 25.0,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.19,
        new_long: 2.4
      },
      geometry: { type: 'Point', coordinates: [2.4, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 33,
        trek: 34,
        wachtsman: null,
        tijd: '21:35',
        datum: '26-1-2018',
        lat: "51°19'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 4,
        'tijd halen': '23:00',
        schatting: null,
        totaal_kg: 60,
        tong: 25,
        schol: 30.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.19,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 34,
        trek: 35,
        wachtsman: null,
        tijd: '23:10',
        datum: '26-1-2018',
        lat: "51°20'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 4,
        'tijd halen': '00:35',
        schatting: null,
        totaal_kg: 40,
        tong: 15,
        schol: 20.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.2,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 35,
        trek: 36,
        wachtsman: null,
        tijd: '00:45',
        datum: '27-1-2018',
        lat: "51°20'",
        long: "02°40'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '02:10',
        schatting: null,
        totaal_kg: 40,
        tong: 17,
        schol: 20.0,
        kabeljauw: null,
        tarbot: 3.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.2,
        new_long: 2.4
      },
      geometry: { type: 'Point', coordinates: [2.4, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 36,
        trek: 37,
        wachtsman: null,
        tijd: '02:20',
        datum: '27-1-2018',
        lat: "51°19'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '03:45',
        schatting: null,
        totaal_kg: 40,
        tong: 20,
        schol: 20.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.19,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 37,
        trek: 38,
        wachtsman: null,
        tijd: '03:55',
        datum: '27-1-2018',
        lat: "51°19'",
        long: "02°38'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '05:20',
        schatting: null,
        totaal_kg: 50,
        tong: 21,
        schol: 25.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.19,
        new_long: 2.38
      },
      geometry: { type: 'Point', coordinates: [2.38, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 38,
        trek: 39,
        wachtsman: null,
        tijd: '05:30',
        datum: '27-1-2018',
        lat: "51°18'",
        long: "03°38'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '06:55',
        schatting: null,
        totaal_kg: 35,
        tong: 15,
        schol: 20.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.18,
        new_long: 3.38
      },
      geometry: { type: 'Point', coordinates: [3.38, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 39,
        trek: 40,
        wachtsman: null,
        tijd: '07:10',
        datum: '27-1-2018',
        lat: "51°18'",
        long: "03°39'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '08:30',
        schatting: null,
        totaal_kg: 25,
        tong: 10,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.18,
        new_long: 3.39
      },
      geometry: { type: 'Point', coordinates: [3.39, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 40,
        trek: 41,
        wachtsman: null,
        tijd: '08:40',
        datum: '27-1-2018',
        lat: "51°18'",
        long: "02°38'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '10:10',
        schatting: null,
        totaal_kg: 65,
        tong: 15,
        schol: 40.0,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.18,
        new_long: 2.38
      },
      geometry: { type: 'Point', coordinates: [2.38, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 41,
        trek: 42,
        wachtsman: null,
        tijd: '10:20',
        datum: '27-1-2018',
        lat: "51°19'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '11:50',
        schatting: null,
        totaal_kg: 50,
        tong: 15,
        schol: 30.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.19,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 42,
        trek: 43,
        wachtsman: null,
        tijd: '12:00',
        datum: '27-1-2018',
        lat: "51°20'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '13:25',
        schatting: null,
        totaal_kg: 55,
        tong: 15,
        schol: 35.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.2,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 43,
        trek: 44,
        wachtsman: null,
        tijd: '13:35',
        datum: '27-1-2018',
        lat: "51°19'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'w',
        'kracht (Bft)': 3,
        'tijd halen': '14:40',
        schatting: null,
        totaal_kg: 15,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.19,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 44,
        trek: 45,
        wachtsman: null,
        tijd: '15:00',
        datum: '27-1-2018',
        lat: "51°17'",
        long: "02°29'",
        snelheid: 4.5,
        richting: 'w',
        'kracht (Bft)': 3,
        'tijd halen': '16:15',
        schatting: null,
        totaal_kg: 10,
        tong: 5,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.17,
        new_long: 2.29
      },
      geometry: { type: 'Point', coordinates: [2.29, 51.17] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 45,
        trek: 46,
        wachtsman: null,
        tijd: '16:25',
        datum: '27-1-2018',
        lat: "51°18'",
        long: "02°27'",
        snelheid: 4.5,
        richting: 'w',
        'kracht (Bft)': 3,
        'tijd halen': '17:20',
        schatting: null,
        totaal_kg: 10,
        tong: 5,
        schol: null,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.18,
        new_long: 2.27
      },
      geometry: { type: 'Point', coordinates: [2.27, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 46,
        trek: 47,
        wachtsman: null,
        tijd: '17:35',
        datum: '27-1-2018',
        lat: "51°17'",
        long: "02°29'",
        snelheid: 4.5,
        richting: 'nw',
        'kracht (Bft)': 3,
        'tijd halen': '19:40',
        schatting: null,
        totaal_kg: 60,
        tong: 20,
        schol: 30.0,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.17,
        new_long: 2.29
      },
      geometry: { type: 'Point', coordinates: [2.29, 51.17] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 47,
        trek: 48,
        wachtsman: null,
        tijd: '19:50',
        datum: '27-1-2018',
        lat: "51°18'",
        long: "02°37'",
        snelheid: 4.5,
        richting: 'nw',
        'kracht (Bft)': 3,
        'tijd halen': '21:20',
        schatting: null,
        totaal_kg: 50,
        tong: 15,
        schol: 30.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.18,
        new_long: 2.37
      },
      geometry: { type: 'Point', coordinates: [2.37, 51.18] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 48,
        trek: 49,
        wachtsman: null,
        tijd: '21:30',
        datum: '27-1-2018',
        lat: "51°19'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'nw',
        'kracht (Bft)': 2,
        'tijd halen': '23:00',
        schatting: null,
        totaal_kg: 20,
        tong: 10,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.19,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 49,
        trek: 50,
        wachtsman: null,
        tijd: '23:10',
        datum: '27-1-2018',
        lat: "51°19'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'nw',
        'kracht (Bft)': 2,
        'tijd halen': '00:00',
        schatting: null,
        totaal_kg: 15,
        tong: 5,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.19,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 50,
        trek: 51,
        wachtsman: null,
        tijd: '00:15',
        datum: '28-1-2018',
        lat: "51°20'",
        long: "02°40'",
        snelheid: 4.5,
        richting: 'nw',
        'kracht (Bft)': 2,
        'tijd halen': '01:45',
        schatting: null,
        totaal_kg: 30,
        tong: 10,
        schol: 15.0,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.2,
        new_long: 2.4
      },
      geometry: { type: 'Point', coordinates: [2.4, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 51,
        trek: 52,
        wachtsman: null,
        tijd: '01:50',
        datum: '28-1-2018',
        lat: "51°19'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'nw',
        'kracht (Bft)': 2,
        'tijd halen': '03:20',
        schatting: null,
        totaal_kg: 50,
        tong: 22,
        schol: 25.0,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.19,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.19] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 52,
        trek: 53,
        wachtsman: null,
        tijd: '03:30',
        datum: '28-1-2018',
        lat: "51°20'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'nw',
        'kracht (Bft)': 2,
        'tijd halen': '05:00',
        schatting: null,
        totaal_kg: 30,
        tong: 13,
        schol: 10.0,
        kabeljauw: null,
        tarbot: 2.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.2,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 53,
        trek: 54,
        wachtsman: null,
        tijd: '05:05',
        datum: '28-1-2018',
        lat: "51°20'",
        long: "02°40'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 2,
        'tijd halen': '06:35',
        schatting: null,
        totaal_kg: 40,
        tong: 17,
        schol: 10.0,
        kabeljauw: null,
        tarbot: 3.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: 10.0,
        new_lat: 51.2,
        new_long: 2.4
      },
      geometry: { type: 'Point', coordinates: [2.4, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 54,
        trek: 55,
        wachtsman: null,
        tijd: '06:45',
        datum: '28-1-2018',
        lat: "51°20'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 2,
        'tijd halen': '08:15',
        schatting: null,
        totaal_kg: 50,
        tong: 20,
        schol: 20.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.2,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 55,
        trek: 56,
        wachtsman: null,
        tijd: '08:25',
        datum: '28-1-2018',
        lat: "51°21'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 4,
        'tijd halen': '09:55',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: 15.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.21,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 56,
        trek: 57,
        wachtsman: null,
        tijd: '10:05',
        datum: '28-1-2018',
        lat: "51°21'",
        long: "02°38'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 5,
        'tijd halen': '11:45',
        schatting: null,
        totaal_kg: 50,
        tong: 15,
        schol: 15.0,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: 10.0,
        new_lat: 51.21,
        new_long: 2.38
      },
      geometry: { type: 'Point', coordinates: [2.38, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 57,
        trek: 58,
        wachtsman: null,
        tijd: '11:55',
        datum: '28-1-2018',
        lat: "51°21'",
        long: "02°37'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 6,
        'tijd halen': '13:25',
        schatting: null,
        totaal_kg: 30,
        tong: 10,
        schol: 10.0,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.21,
        new_long: 2.37
      },
      geometry: { type: 'Point', coordinates: [2.37, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 58,
        trek: 59,
        wachtsman: null,
        tijd: '13:35',
        datum: '28-1-2018',
        lat: "51°21'",
        long: "02°39'",
        snelheid: 4.5,
        richting: 'zzw',
        'kracht (Bft)': 6,
        'tijd halen': '15:05',
        schatting: null,
        totaal_kg: 30,
        tong: 10,
        schol: 10.0,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: 5.0,
        new_lat: 51.21,
        new_long: 2.39
      },
      geometry: { type: 'Point', coordinates: [2.39, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 59,
        trek: 60,
        wachtsman: null,
        tijd: '15:15',
        datum: '28-1-2018',
        lat: "51°21'",
        long: "02°41'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 6,
        'tijd halen': '16:45',
        schatting: null,
        totaal_kg: 45,
        tong: 10,
        schol: 15.0,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: 10.0,
        new_lat: 51.21,
        new_long: 2.41
      },
      geometry: { type: 'Point', coordinates: [2.41, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 60,
        trek: 61,
        wachtsman: null,
        tijd: '16:55',
        datum: '28-1-2018',
        lat: "51°20'",
        long: "02°41'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 6,
        'tijd halen': '18:25',
        schatting: null,
        totaal_kg: 25,
        tong: 5,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: 5.0,
        new_lat: 51.2,
        new_long: 2.41
      },
      geometry: { type: 'Point', coordinates: [2.41, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 61,
        trek: 62,
        wachtsman: null,
        tijd: '18:35',
        datum: '28-1-2018',
        lat: "51°20'",
        long: "02°41'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 7,
        'tijd halen': '20:15',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: 10.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.2,
        new_long: 2.41
      },
      geometry: { type: 'Point', coordinates: [2.41, 51.2] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 62,
        trek: 63,
        wachtsman: null,
        tijd: '20:25',
        datum: '28-1-2018',
        lat: "51°21'",
        long: "02°42'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 7,
        'tijd halen': '21:40',
        schatting: null,
        totaal_kg: 25,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.21,
        new_long: 2.42
      },
      geometry: { type: 'Point', coordinates: [2.42, 51.21] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 63,
        trek: 64,
        wachtsman: null,
        tijd: '21:50',
        datum: '28-1-2018',
        lat: "51°25'",
        long: "02°48'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 6,
        'tijd halen': '23:10',
        schatting: null,
        totaal_kg: 20,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.25,
        new_long: 2.48
      },
      geometry: { type: 'Point', coordinates: [2.48, 51.25] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 64,
        trek: 65,
        wachtsman: null,
        tijd: '23:20',
        datum: '28-1-2018',
        lat: "51°24'",
        long: "02°47'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 6,
        'tijd halen': '01:00',
        schatting: null,
        totaal_kg: 25,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.24,
        new_long: 2.47
      },
      geometry: { type: 'Point', coordinates: [2.47, 51.24] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 65,
        trek: 66,
        wachtsman: null,
        tijd: '01:10',
        datum: '29-1-2018',
        lat: "51°26'",
        long: "02°55'",
        snelheid: 4.5,
        richting: 'wzw',
        'kracht (Bft)': 5,
        'tijd halen': '02:40',
        schatting: null,
        totaal_kg: 30,
        tong: 26,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.26,
        new_long: 2.55
      },
      geometry: { type: 'Point', coordinates: [2.55, 51.26] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 66,
        trek: 67,
        wachtsman: null,
        tijd: '02:50',
        datum: '29-1-2018',
        lat: "51°30'",
        long: "03°04'",
        snelheid: 4.5,
        richting: 'wzw',
        'kracht (Bft)': 4,
        'tijd halen': '04:15',
        schatting: null,
        totaal_kg: 25,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: 2.0,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.3,
        new_long: 3.04
      },
      geometry: { type: 'Point', coordinates: [3.04, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 67,
        trek: 68,
        wachtsman: null,
        tijd: '04:30',
        datum: '29-1-2018',
        lat: "51°28'",
        long: "02°58'",
        snelheid: 4.5,
        richting: 'wzw',
        'kracht (Bft)': 4,
        'tijd halen': '05:55',
        schatting: null,
        totaal_kg: 30,
        tong: 23,
        schol: null,
        kabeljauw: 2.0,
        tarbot: 2.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.28,
        new_long: 2.58
      },
      geometry: { type: 'Point', coordinates: [2.58, 51.28] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 68,
        trek: 69,
        wachtsman: null,
        tijd: '06:05',
        datum: '29-1-2018',
        lat: "51°31'",
        long: "03°06'",
        snelheid: 4.5,
        richting: 'wzw',
        'kracht (Bft)': 4,
        'tijd halen': '07:30',
        schatting: null,
        totaal_kg: 25,
        tong: 23,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.31,
        new_long: 3.06
      },
      geometry: { type: 'Point', coordinates: [3.06, 51.31] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 69,
        trek: 70,
        wachtsman: null,
        tijd: '07:40',
        datum: '29-1-2018',
        lat: "51°28'",
        long: "02°58'",
        snelheid: 4.5,
        richting: 'wzw',
        'kracht (Bft)': 4,
        'tijd halen': '08:55',
        schatting: null,
        totaal_kg: 20,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.28,
        new_long: 2.58
      },
      geometry: { type: 'Point', coordinates: [2.58, 51.28] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 70,
        trek: 71,
        wachtsman: null,
        tijd: '09:00',
        datum: '29-1-2018',
        lat: "51°31'",
        long: "03°06'",
        snelheid: 4.5,
        richting: 'wzw',
        'kracht (Bft)': 4,
        'tijd halen': '10:25',
        schatting: null,
        totaal_kg: 20,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.31,
        new_long: 3.06
      },
      geometry: { type: 'Point', coordinates: [3.06, 51.31] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 71,
        trek: 72,
        wachtsman: null,
        tijd: '10:35',
        datum: '29-1-2018',
        lat: "51°29'",
        long: "02°59'",
        snelheid: 4.5,
        richting: 'wzw',
        'kracht (Bft)': 4,
        'tijd halen': '12:05',
        schatting: null,
        totaal_kg: 40,
        tong: 25,
        schol: 5.0,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: 5.0,
        new_lat: 51.29,
        new_long: 2.59
      },
      geometry: { type: 'Point', coordinates: [2.59, 51.29] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 72,
        trek: 73,
        wachtsman: null,
        tijd: '12:15',
        datum: '29-1-2018',
        lat: "51°32'",
        long: "03°08'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 5,
        'tijd halen': '13:05',
        schatting: null,
        totaal_kg: 15,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.32,
        new_long: 3.08
      },
      geometry: { type: 'Point', coordinates: [3.08, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 73,
        trek: 74,
        wachtsman: null,
        tijd: '13:15',
        datum: '29-1-2018',
        lat: "51°34'",
        long: "03°15'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 6,
        'tijd halen': '14:15',
        schatting: null,
        totaal_kg: 20,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.15
      },
      geometry: { type: 'Point', coordinates: [3.15, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 74,
        trek: 75,
        wachtsman: null,
        tijd: '14:25',
        datum: '29-1-2018',
        lat: "51°34'",
        long: "03°15'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 6,
        'tijd halen': '15:40',
        schatting: null,
        totaal_kg: 25,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.15
      },
      geometry: { type: 'Point', coordinates: [3.15, 51.34] }
    }
  ]
}
