export default {
  type: 'FeatureCollection',
  name: 'week_2',
  crs: { type: 'name', properties: { name: 'urn:ogc:def:crs:OGC:1.3:CRS84' } },
  features: [
    {
      type: 'Feature',
      properties: {
        field_1: 0,
        trek: 1,
        wachtsman: null,
        tijd: '06:00',
        datum: '8-1-2018',
        lat: "51°37'",
        long: "03°20'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '07:05',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: 5.0,
        new_lat: 51.37,
        new_long: 3.2
      },
      geometry: { type: 'Point', coordinates: [3.2, 51.37] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 1,
        trek: 2,
        wachtsman: null,
        tijd: '07:10',
        datum: '8-1-2018',
        lat: "51°34'",
        long: "03°15'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '08:30',
        schatting: null,
        totaal_kg: 45,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: 10.0,
        new_lat: 51.34,
        new_long: 3.15
      },
      geometry: { type: 'Point', coordinates: [3.15, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 2,
        trek: 3,
        wachtsman: null,
        tijd: '10:15',
        datum: '8-1-2018',
        lat: "51°32'",
        long: "03°08'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '10:05',
        schatting: null,
        totaal_kg: 60,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 25.0,
        schar: 10.0,
        new_lat: 51.32,
        new_long: 3.08
      },
      geometry: { type: 'Point', coordinates: [3.08, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 3,
        trek: 4,
        wachtsman: null,
        tijd: '11:45',
        datum: '8-1-2018',
        lat: "51°34'",
        long: "03°14'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '11:35',
        schatting: null,
        totaal_kg: 40,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: 5.0,
        new_lat: 51.34,
        new_long: 3.14
      },
      geometry: { type: 'Point', coordinates: [3.14, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 4,
        trek: 5,
        wachtsman: null,
        tijd: '13:10',
        datum: '8-1-2018',
        lat: "51°36'",
        long: "03°17'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '13:00',
        schatting: null,
        totaal_kg: 55,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 20.0,
        schar: 10.0,
        new_lat: 51.36,
        new_long: 3.17
      },
      geometry: { type: 'Point', coordinates: [3.17, 51.36] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 5,
        trek: 6,
        wachtsman: null,
        tijd: '14:35',
        datum: '8-1-2018',
        lat: "51°32'",
        long: "03°07'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '14:25',
        schatting: null,
        totaal_kg: 40,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 20.0,
        schar: null,
        new_lat: 51.32,
        new_long: 3.07
      },
      geometry: { type: 'Point', coordinates: [3.07, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 6,
        trek: 7,
        wachtsman: null,
        tijd: '15:50',
        datum: '8-1-2018',
        lat: "51°33'",
        long: "03°13'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '15:40',
        schatting: null,
        totaal_kg: 40,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 20.0,
        schar: null,
        new_lat: 51.33,
        new_long: 3.13
      },
      geometry: { type: 'Point', coordinates: [3.13, 51.33] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 7,
        trek: 8,
        wachtsman: null,
        tijd: '17:20',
        datum: '8-1-2018',
        lat: "51°31'",
        long: "03°05'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '17:10',
        schatting: null,
        totaal_kg: 55,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 25.0,
        schar: 10.0,
        new_lat: 51.31,
        new_long: 3.05
      },
      geometry: { type: 'Point', coordinates: [3.05, 51.31] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 8,
        trek: 9,
        wachtsman: null,
        tijd: '18:50',
        datum: '8-1-2018',
        lat: "51°30'",
        long: "03°03'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 6,
        'tijd halen': '18:40',
        schatting: null,
        totaal_kg: 50,
        tong: 30,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 15.0,
        schar: null,
        new_lat: 51.3,
        new_long: 3.03
      },
      geometry: { type: 'Point', coordinates: [3.03, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 9,
        trek: 10,
        wachtsman: null,
        tijd: '20:25',
        datum: '8-1-2018',
        lat: "51°31'",
        long: "03°04'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '20:15',
        schatting: null,
        totaal_kg: 45,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 20.0,
        schar: null,
        new_lat: 51.31,
        new_long: 3.04
      },
      geometry: { type: 'Point', coordinates: [3.04, 51.31] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 10,
        trek: 11,
        wachtsman: null,
        tijd: '22:00',
        datum: '8-1-2018',
        lat: "51°34'",
        long: "03°13'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '21:50',
        schatting: null,
        totaal_kg: 40,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.34,
        new_long: 3.13
      },
      geometry: { type: 'Point', coordinates: [3.13, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 11,
        trek: 12,
        wachtsman: null,
        tijd: '23:30',
        datum: '8-1-2018',
        lat: "51°36'",
        long: "03°18'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '23:20',
        schatting: null,
        totaal_kg: 35,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: null,
        new_lat: 51.36,
        new_long: 3.18
      },
      geometry: { type: 'Point', coordinates: [3.18, 51.36] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 12,
        trek: 13,
        wachtsman: null,
        tijd: '01:00',
        datum: '9-1-2018',
        lat: "51°35'",
        long: "03°17'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '00:50',
        schatting: null,
        totaal_kg: 35,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 15.0,
        schar: null,
        new_lat: 51.35,
        new_long: 3.17
      },
      geometry: { type: 'Point', coordinates: [3.17, 51.35] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 13,
        trek: 14,
        wachtsman: null,
        tijd: '02:25',
        datum: '9-1-2018',
        lat: "51°36'",
        long: "03°17'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '02:15',
        schatting: null,
        totaal_kg: 35,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.36,
        new_long: 3.17
      },
      geometry: { type: 'Point', coordinates: [3.17, 51.36] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 14,
        trek: 15,
        wachtsman: null,
        tijd: '03:40',
        datum: '9-1-2018',
        lat: "51°32'",
        long: "03°07'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '03:30',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.32,
        new_long: 3.07
      },
      geometry: { type: 'Point', coordinates: [3.07, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 15,
        trek: 16,
        wachtsman: null,
        tijd: '05:00',
        datum: '9-1-2018',
        lat: "51°29'",
        long: "03°00'",
        snelheid: 4.5,
        richting: 'no',
        'kracht (Bft)': 5,
        'tijd halen': '04:50',
        schatting: null,
        totaal_kg: 10,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.29,
        new_long: 3.0
      },
      geometry: { type: 'Point', coordinates: [3.0, 51.29] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 16,
        trek: 17,
        wachtsman: null,
        tijd: '06:30',
        datum: '9-1-2018',
        lat: "51°30'",
        long: "02°57'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 4,
        'tijd halen': '06:20',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: null,
        new_lat: 51.3,
        new_long: 2.57
      },
      geometry: { type: 'Point', coordinates: [2.57, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 17,
        trek: 18,
        wachtsman: null,
        tijd: '07:45',
        datum: '9-1-2018',
        lat: "51°30'",
        long: "03°04'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 4,
        'tijd halen': '07:30',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: 10.0,
        new_lat: 51.3,
        new_long: 3.04
      },
      geometry: { type: 'Point', coordinates: [3.04, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 18,
        trek: 19,
        wachtsman: null,
        tijd: '08:55',
        datum: '9-1-2018',
        lat: "51°32'",
        long: "03°06'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 4,
        'tijd halen': '08:45',
        schatting: null,
        totaal_kg: 35,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: 10.0,
        new_lat: 51.32,
        new_long: 3.06
      },
      geometry: { type: 'Point', coordinates: [3.06, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 19,
        trek: 20,
        wachtsman: null,
        tijd: '10:20',
        datum: '9-1-2018',
        lat: "51°34'",
        long: "03°14'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 4,
        'tijd halen': '10:05',
        schatting: null,
        totaal_kg: 40,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: 5.0,
        new_lat: 51.34,
        new_long: 3.14
      },
      geometry: { type: 'Point', coordinates: [3.14, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 20,
        trek: 21,
        wachtsman: null,
        tijd: '11:40',
        datum: '9-1-2018',
        lat: "51°34'",
        long: "03°14'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 4,
        'tijd halen': '11:30',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: 10.0,
        new_lat: 51.34,
        new_long: 3.14
      },
      geometry: { type: 'Point', coordinates: [3.14, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 21,
        trek: 22,
        wachtsman: null,
        tijd: '12:50',
        datum: '9-1-2018',
        lat: "51°34'",
        long: "03°15'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 4,
        'tijd halen': '12:40',
        schatting: null,
        totaal_kg: 35,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: 10.0,
        new_lat: 51.34,
        new_long: 3.15
      },
      geometry: { type: 'Point', coordinates: [3.15, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 22,
        trek: 23,
        wachtsman: null,
        tijd: '13:50',
        datum: '9-1-2018',
        lat: "51°32'",
        long: "03°07'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 3,
        'tijd halen': '13:40',
        schatting: null,
        totaal_kg: 55,
        tong: 5,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 45.0,
        schar: null,
        new_lat: 51.32,
        new_long: 3.07
      },
      geometry: { type: 'Point', coordinates: [3.07, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 23,
        trek: 24,
        wachtsman: null,
        tijd: '15:15',
        datum: '9-1-2018',
        lat: "51°30'",
        long: "03°06'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 3,
        'tijd halen': '15:05',
        schatting: null,
        totaal_kg: 65,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 45.0,
        schar: null,
        new_lat: 51.3,
        new_long: 3.06
      },
      geometry: { type: 'Point', coordinates: [3.06, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 24,
        trek: 25,
        wachtsman: null,
        tijd: '16:40',
        datum: '9-1-2018',
        lat: "51°29'",
        long: "03°00'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 3,
        'tijd halen': '16:30',
        schatting: null,
        totaal_kg: 50,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 30.0,
        schar: null,
        new_lat: 51.29,
        new_long: 3.0
      },
      geometry: { type: 'Point', coordinates: [3.0, 51.29] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 25,
        trek: 26,
        wachtsman: null,
        tijd: '18:00',
        datum: '9-1-2018',
        lat: "51°29'",
        long: "03°03'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '17:50',
        schatting: null,
        totaal_kg: 35,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.29,
        new_long: 3.03
      },
      geometry: { type: 'Point', coordinates: [3.03, 51.29] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 26,
        trek: 27,
        wachtsman: null,
        tijd: '19:25',
        datum: '9-1-2018',
        lat: "51°31'",
        long: "03°06'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '19:15',
        schatting: null,
        totaal_kg: 30,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: null,
        new_lat: 51.31,
        new_long: 3.06
      },
      geometry: { type: 'Point', coordinates: [3.06, 51.31] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 27,
        trek: 28,
        wachtsman: null,
        tijd: '20:50',
        datum: '9-1-2018',
        lat: "51°33'",
        long: "03°08'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '20:40',
        schatting: null,
        totaal_kg: 30,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.33,
        new_long: 3.08
      },
      geometry: { type: 'Point', coordinates: [3.08, 51.33] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 28,
        trek: 29,
        wachtsman: null,
        tijd: '22:15',
        datum: '9-1-2018',
        lat: "51°34'",
        long: "03°11'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '22:05',
        schatting: null,
        totaal_kg: 15,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.11
      },
      geometry: { type: 'Point', coordinates: [3.11, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 29,
        trek: 30,
        wachtsman: null,
        tijd: '23:35',
        datum: '9-1-2018',
        lat: "51°32'",
        long: "03°06'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '23:15',
        schatting: null,
        totaal_kg: 30,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.32,
        new_long: 3.06
      },
      geometry: { type: 'Point', coordinates: [3.06, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 30,
        trek: 31,
        wachtsman: null,
        tijd: '01:10',
        datum: '10-1-2018',
        lat: "51°34'",
        long: "03°10'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '01:00',
        schatting: null,
        totaal_kg: 40,
        tong: 35,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.1
      },
      geometry: { type: 'Point', coordinates: [3.1, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 31,
        trek: 32,
        wachtsman: null,
        tijd: '01:20',
        datum: '10-1-2018',
        lat: "51°34'",
        long: "03°11'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '02:35',
        schatting: null,
        totaal_kg: 21,
        tong: 21,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.11
      },
      geometry: { type: 'Point', coordinates: [3.11, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 32,
        trek: 33,
        wachtsman: null,
        tijd: '02:45',
        datum: '10-1-2018',
        lat: "51°32'",
        long: "03°06'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 3,
        'tijd halen': '04:00',
        schatting: null,
        totaal_kg: 28,
        tong: 28,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.32,
        new_long: 3.06
      },
      geometry: { type: 'Point', coordinates: [3.06, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 33,
        trek: 34,
        wachtsman: null,
        tijd: '04:10',
        datum: '10-1-2018',
        lat: "51°34'",
        long: "03°09'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 2,
        'tijd halen': '05:25',
        schatting: null,
        totaal_kg: 22,
        tong: 22,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.09
      },
      geometry: { type: 'Point', coordinates: [3.09, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 34,
        trek: 35,
        wachtsman: null,
        tijd: '05:30',
        datum: '10-1-2018',
        lat: "51°34'",
        long: "03°10'",
        snelheid: 4.5,
        richting: 'zw',
        'kracht (Bft)': 2,
        'tijd halen': '06:50',
        schatting: null,
        totaal_kg: 22,
        tong: 22,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.1
      },
      geometry: { type: 'Point', coordinates: [3.1, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 35,
        trek: 36,
        wachtsman: null,
        tijd: '07:00',
        datum: '10-1-2018',
        lat: "51°32'",
        long: "03°06'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 2,
        'tijd halen': '08:15',
        schatting: null,
        totaal_kg: 22,
        tong: 22,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.32,
        new_long: 3.06
      },
      geometry: { type: 'Point', coordinates: [3.06, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 36,
        trek: 37,
        wachtsman: null,
        tijd: '08:25',
        datum: '10-1-2018',
        lat: "51°34'",
        long: "03°09'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 3,
        'tijd halen': '09:50',
        schatting: null,
        totaal_kg: 20,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.09
      },
      geometry: { type: 'Point', coordinates: [3.09, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 37,
        trek: 38,
        wachtsman: null,
        tijd: '10:00',
        datum: '10-1-2018',
        lat: "51°34'",
        long: "03°10'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 3,
        'tijd halen': '11:10',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: null,
        new_lat: 51.34,
        new_long: 3.1
      },
      geometry: { type: 'Point', coordinates: [3.1, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 38,
        trek: 39,
        wachtsman: null,
        tijd: '11:20',
        datum: '10-1-2018',
        lat: "51°34'",
        long: "03°13'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 3,
        'tijd halen': '12:45',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: null,
        new_lat: 51.34,
        new_long: 3.13
      },
      geometry: { type: 'Point', coordinates: [3.13, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 39,
        trek: 40,
        wachtsman: null,
        tijd: '12:55',
        datum: '10-1-2018',
        lat: "51°34'",
        long: "03°12'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 3,
        'tijd halen': '14:20',
        schatting: null,
        totaal_kg: 15,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.34,
        new_long: 3.12
      },
      geometry: { type: 'Point', coordinates: [3.12, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 40,
        trek: 41,
        wachtsman: null,
        tijd: '14:30',
        datum: '10-1-2018',
        lat: "51°33'",
        long: "03°11'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 3,
        'tijd halen': '15:40',
        schatting: null,
        totaal_kg: 10,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.33,
        new_long: 3.11
      },
      geometry: { type: 'Point', coordinates: [3.11, 51.33] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 41,
        trek: 42,
        wachtsman: null,
        tijd: '15:50',
        datum: '10-1-2018',
        lat: "51°33'",
        long: "03°08'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 3,
        'tijd halen': '16:55',
        schatting: null,
        totaal_kg: 15,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.33,
        new_long: 3.08
      },
      geometry: { type: 'Point', coordinates: [3.08, 51.33] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 42,
        trek: 43,
        wachtsman: null,
        tijd: '17:05',
        datum: '10-1-2018',
        lat: "51°34'",
        long: "03°14'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 2,
        'tijd halen': '18:10',
        schatting: null,
        totaal_kg: 35,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 20.0,
        schar: null,
        new_lat: 51.34,
        new_long: 3.14
      },
      geometry: { type: 'Point', coordinates: [3.14, 51.34] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 43,
        trek: 44,
        wachtsman: null,
        tijd: '18:20',
        datum: '10-1-2018',
        lat: "51°32'",
        long: "03°07'",
        snelheid: 4.5,
        richting: 'zo',
        'kracht (Bft)': 2,
        'tijd halen': '19:50',
        schatting: null,
        totaal_kg: 30,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.32,
        new_long: 3.07
      },
      geometry: { type: 'Point', coordinates: [3.07, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 44,
        trek: 45,
        wachtsman: null,
        tijd: '20:00',
        datum: '10-1-2018',
        lat: "51°31'",
        long: "03°03'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 2,
        'tijd halen': '21:25',
        schatting: null,
        totaal_kg: 25,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.31,
        new_long: 3.03
      },
      geometry: { type: 'Point', coordinates: [3.03, 51.31] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 45,
        trek: 46,
        wachtsman: null,
        tijd: '21:35',
        datum: '10-1-2018',
        lat: "51°31'",
        long: "03°03'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 2,
        'tijd halen': '23:05',
        schatting: null,
        totaal_kg: 20,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.31,
        new_long: 3.03
      },
      geometry: { type: 'Point', coordinates: [3.03, 51.31] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 46,
        trek: 47,
        wachtsman: null,
        tijd: '23:15',
        datum: '10-1-2018',
        lat: "51°30'",
        long: "03°02'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 2,
        'tijd halen': '00:40',
        schatting: null,
        totaal_kg: 15,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.3,
        new_long: 3.02
      },
      geometry: { type: 'Point', coordinates: [3.02, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 47,
        trek: 48,
        wachtsman: null,
        tijd: '00:50',
        datum: '11-1-2018',
        lat: "51°33'",
        long: "03°10'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 2,
        'tijd halen': '01:45',
        schatting: null,
        totaal_kg: 20,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: null,
        schar: null,
        new_lat: 51.33,
        new_long: 3.1
      },
      geometry: { type: 'Point', coordinates: [3.1, 51.33] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 48,
        trek: 49,
        wachtsman: null,
        tijd: '01:55',
        datum: '11-1-2018',
        lat: "51°33'",
        long: "03°12'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 2,
        'tijd halen': '03:10',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 15.0,
        schar: null,
        new_lat: 51.33,
        new_long: 3.12
      },
      geometry: { type: 'Point', coordinates: [3.12, 51.33] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 49,
        trek: 50,
        wachtsman: null,
        tijd: '03:15',
        datum: '11-1-2018',
        lat: "51°30'",
        long: "03°04'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 2,
        'tijd halen': '04:30',
        schatting: null,
        totaal_kg: 40,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: 5.0,
        griet: null,
        rog: 5.0,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.3,
        new_long: 3.04
      },
      geometry: { type: 'Point', coordinates: [3.04, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 50,
        trek: 51,
        wachtsman: null,
        tijd: '04:40',
        datum: '11-1-2018',
        lat: "51°32'",
        long: "03°04'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 2,
        'tijd halen': '05:55',
        schatting: null,
        totaal_kg: 22,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: 2.0,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 5.0,
        schar: null,
        new_lat: 51.32,
        new_long: 3.04
      },
      geometry: { type: 'Point', coordinates: [3.04, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 51,
        trek: 52,
        wachtsman: null,
        tijd: '06:00',
        datum: '11-1-2018',
        lat: "51°30'",
        long: "03°01'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 2,
        'tijd halen': '07:20',
        schatting: null,
        totaal_kg: 35,
        tong: 25,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.3,
        new_long: 3.01
      },
      geometry: { type: 'Point', coordinates: [3.01, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 52,
        trek: 53,
        wachtsman: null,
        tijd: '07:30',
        datum: '11-1-2018',
        lat: "51°30'",
        long: "03°01'",
        snelheid: 4.5,
        richting: 'z',
        'kracht (Bft)': 2,
        'tijd halen': '09:05',
        schatting: null,
        totaal_kg: 35,
        tong: 20,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.3,
        new_long: 3.01
      },
      geometry: { type: 'Point', coordinates: [3.01, 51.3] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 53,
        trek: 54,
        wachtsman: null,
        tijd: '09:15',
        datum: '11-1-2018',
        lat: "51°31'",
        long: "03°02'",
        snelheid: 4.5,
        richting: 'variabel',
        'kracht (Bft)': 0,
        'tijd halen': '10:40',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.31,
        new_long: 3.02
      },
      geometry: { type: 'Point', coordinates: [3.02, 51.31] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 54,
        trek: 55,
        wachtsman: null,
        tijd: '10:50',
        datum: '11-1-2018',
        lat: "51°32'",
        long: "03°04'",
        snelheid: 4.5,
        richting: 'variabel',
        'kracht (Bft)': 0,
        'tijd halen': '12:15',
        schatting: null,
        totaal_kg: 25,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.32,
        new_long: 3.04
      },
      geometry: { type: 'Point', coordinates: [3.04, 51.32] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 55,
        trek: 56,
        wachtsman: null,
        tijd: '12:25',
        datum: '11-1-2018',
        lat: "51°31'",
        long: "03°01'",
        snelheid: 4.5,
        richting: 'variabel',
        'kracht (Bft)': 0,
        'tijd halen': '13:50',
        schatting: null,
        totaal_kg: 30,
        tong: 15,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.31,
        new_long: 3.01
      },
      geometry: { type: 'Point', coordinates: [3.01, 51.31] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 56,
        trek: 57,
        wachtsman: null,
        tijd: '14:00',
        datum: '11-1-2018',
        lat: "51°33'",
        long: "03°07'",
        snelheid: 4.5,
        richting: 'variabel',
        'kracht (Bft)': 0,
        'tijd halen': '15:30',
        schatting: null,
        totaal_kg: 25,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.33,
        new_long: 3.07
      },
      geometry: { type: 'Point', coordinates: [3.07, 51.33] }
    },
    {
      type: 'Feature',
      properties: {
        field_1: 57,
        trek: 58,
        wachtsman: null,
        tijd: '15:40',
        datum: '11-1-2018',
        lat: "51°32'",
        long: "03°03'",
        snelheid: 4.5,
        richting: 'variabel',
        'kracht (Bft)': 0,
        'tijd halen': '17:00',
        schatting: null,
        totaal_kg: 25,
        tong: 10,
        schol: null,
        kabeljauw: null,
        tarbot: null,
        griet: null,
        rog: null,
        opmerkingen: null,
        bot: 10.0,
        schar: null,
        new_lat: 51.32,
        new_long: 3.03
      },
      geometry: { type: 'Point', coordinates: [3.03, 51.32] }
    }
  ]
}
